name: 🚀 Deploy

on:
  push:
    branches: [ main,feature/web ]

jobs:
  test-and-deploy:
    name: 🎉 Export and Deploy
    runs-on: ubuntu-latest 
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
      
      - name: 📂 Sync files
        uses: appleboy/scp-action@master
        with: 
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASS }}
          source: "."
          target: ${{ secrets.DEPLOY_PATH }}
          strip_components: 1

      - name: 🥳 Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASS }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            pm2 -s stop play
            rm -rf ./dist
            mkdir ./dist
            cp server.py ./dist/server.py
            rm constants.gd
            cp constants.deploy constants.gd
            ../Godot --headless --export-debug "Web"
            pm2 -s restart play