name: 🚀 Deploy

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    name: 🎉 Export and Deploy
    runs-on: ubuntu-latest 
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
      
      - name: 🔨 Export Project
        id: export
        # Use latest version (see releases for all versions)
        uses: firebelley/godot-export@v5.2.0
        with:
          # Defining all the required inputs
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
      - name: 🔨 Export Project
        run: |
          mkdir dist
          cp /home/runner/.local/share/godot/archives/Web.zip ./dist/Web.zip

#      - name: 🔨 Export Project
#        run: |
#          wget https://downloads.tuxfamily.org/godotengine/4.1.1/Godot_v4.1.1-stable_linux.x86_64.zip
#          wget https://downloads.tuxfamily.org/godotengine/4.1.1/Godot_v4.1.1-stable_export_templates.tpz
#          unzip Godot_v4.1.1-stable_linux.x86_64.zip
#          ls
#          godot --install-export-templates --export-release --headless ./project.godot Web
#          ls

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          local-dir: ./dist/
          server: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASS }}
